### ISSUE TITLE
Update steps should have prior-state indexes for UIKit batch updates

### ISSUE THREAD

**Issue by bm-w** [andre-alves/PHDiff#3]
Hi there,

You claim that `PHDiff.steps` returns steps ready for use in batch updates of `UICollectionView` (etc.), but if I’m correct this doesn’t seem to be the case. The `performBatchUpdates` docs state that it expects deletion indexes relative to the previous state, and the inserts relative to the post-deletion state:

> Deletes are processed before inserts in batch operations. This means the indexes for the deletions are processed relative to the indexes of the collection view’s state before the batch operation, and the indexes for the insertions are processed relative to the indexes of the state after all the deletions in the batch operation.

It doesn’t explicitly state what it expects for reloads, but it looks like it expects the indexed relative to the previous state as well (this error message hints that UIKit may treat a reload as a deletion followed by an insertion: “attempt to delete item 1 from section 0 which only contains 1 item before the update”).

You return indexes relative to the end state for `update`s, which `performBatchUpdates` gets very unhappy about. To reproduce, e.g.:

- have a `UICollectionView` with one item (i.e. you have an item `[b]`);
- get steps form `PHDiff.steps` to end up with `[A, B]` (`A` is new, `B` is updated from `b`; i.e. get steps `[.insert(A, index: 0), .update(B, index: 1)]`;
- pass these steps to the `UICollectionView`’s `performBatchUpdates` method & friends, and get the error.

To remedy that example, change the steps to `[.insert(A, index: 0), .update(B, index: 0)]` (i.e. change the index of the second step, the update step, to 0), pass those to `UICollectionView`, and voilà.

It seems it’s easily fixed by changing https://github.com/andre-alves/PHDiff/blob/dbe938dfa7567f0adf14b037620fb6ecb8293dcf/PHDiff/PHDiff/Sources/PHDiff.swift#L48 to read:

    steps.append(.update(value: context.toArray[i], index: j))

**Comment by andre-alves** [comment]
Thanks for opening this issue,  you are right!

https://developer.apple.com/documentation/uikit/uitableview/1614935-reloadrows

> When this method is called in an animation block defined by the  beginUpdates() and endUpdates() methods, it behaves similarly to deleteRows(at:with:). The indexes that UITableView passes to the method are specified in the state of the table view prior to any updates.

I did the fix in a new branch **feature/fix-batch-updates**  https://github.com/andre-alves/PHDiff/commit/82b57ae00862cb6f98946f0f626960e55c21d3c1 and added a test case: https://github.com/andre-alves/PHDiff/commit/16ac2ea440f5e68f41c0574c90086c84dea000e6.

I also had to fix the `sortedSteps` by sorting updates first since i'm using old indexes now.

I'm just wondering if I let some case slip but I don't think so.

What do you think?

**Comment by andre-alves** [comment]
Merged in **1.0.7**
